### DISCUSSION TITLE
repo.magento.com proxy lazy sync

### DISCUSSION THREAD

**Discussion by indykoning** [vtsykun/packeton#134] [Q&A] [answered]
I've been trying to set up a mirror for repo.magento.com and while the package listings work correctly, the package metadata will always return a 404 when i enable sync_lazy
```yaml
packeton:
  mirrors:
    magento:
      url: "https://repo.magento.com/"
      public_access: false
      sync_lazy: true
      enable_dist_mirror: true
      http_basic:
        username: xxxx
        password: xxxx
      composer_auth: '{"username": "xxxx", "password": "xxxx"}'
      sync_interval: 3600
      info_cmd_message: "Magento Mirror"
```

When i set sync_lazy to false my package listings do work again, but since the magento repo is pretty full of unnecessary packages it is quite a bit of bloat which would be prevented by using sync_lazy.

Is this because Magento only supports V1 and that does not work with lazy syncs or am i doing something wrong?
