### DISCUSSION TITLE
Error when updating package

### DISCUSSION THREAD

**Discussion by dimasdario** [vtsykun/packeton#139] [General]
Hello, Sorry if I'm in the wrong place to post this question.
I uploaded the project in Docker, made the necessary settings with the ssh key in the recommended format and with OAuth, as you can see below:

![img1](https://github.com/vtsykun/packeton/assets/503853/42f4637b-9ac4-4f0e-90cb-7ecde5ef1738)

I managed to clone the bitbucket project, but in the first update I got the following error:

![img2](https://github.com/vtsykun/packeton/assets/503853/cb44007b-1505-416b-a92b-758756eaa5a6)

I couldn't identify where I'm failing, I can't make it work either with OAuth or with SSH key. Any idea?

**Comment by vtsykun** [comment]
Hi, I see a warning message.

```
if ($credentials && empty($credentials->getKey()) && empty($credentials->getComposerConfig())) {
     $io->warning("SSH Key ...");
}

The SSH key is not loaded from the database, APP_SECRET parameter was probably changed.
```
APP_SECRET used to encrypt a ssh key in database. If you change the value of this parameter, then the ssh key will not be decrypted and the key value will be empty, however it is not empty in screenshot.

Maybe docker config problem leads to uses differents `APP_SECRET` env variable value in CLI and FPM

**Reply by vtsykun** [reply]
I checked this bug on demo and seems it works ok 
![Selection_1617](https://github.com/vtsykun/packeton/assets/21358010/9bc83598-0fd9-4645-9555-cd910cb73b3f)

https://demo.packeton.org/packages/packeton/cache

**Reply by dimasdario** [reply]
Thanks @vtsykun for the explanation, I did the installation again and for single container it works as expected, but for split container the same error continues.

I was guided by the section [Build and run docker container with docker-compose](https://docs.packeton.org/installation-docker.html#build-and-run-docker-container-with-docker-compose)


## Single container

1. change in `docker-compose.yml` file.

>from:

```yaml
environment:
#   ADMIN_USER: admin
#   ADMIN_PASSWORD: 123456
#   ADMIN_EMAIL: admin@example.com
    TRUSTED_PROXIES: 172.16.0.0/12
    # Default SQLite
    DATABASE_URL: "mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=8&charset=utf8mb4"
```

>to:
```yaml
environment:
    ADMIN_USER: admin
    ADMIN_PASSWORD: 123456
    ADMIN_EMAIL: admin@example.com
    TRUSTED_PROXIES: 172.16.0.0/12
    # Default SQLite
    DATABASE_URL: "sqlite:///%kernel.project_dir%/var/app.db"
```

2. Container up

```console
docker@packeton:~$ docker-compose up -d
```

### sucess
![single-sucess](https://github.com/vtsykun/packeton/assets/503853/12d29170-cb03-40a3-ab8f-0471f2a7640c)


## Split container
1. build
```console
docker@packeton:~$ docker compose build --no-cache
```

2. change in `docker-compose-split.yml` file due to my version of docker compose. 


**error found**

![img1](https://github.com/vtsykun/packeton/assets/503853/40c46153-6c5d-4458-b6aa-167f5c941ec2)


>from
```yaml
<<: *restart_policy
<<: *default-volume
```

>to
```yaml
<< : [*restart_policy, *default-volume]
```

3. Change syntax `docker compose` command
>from
```console
docker@packeton:~$ docker-compose up -f docker-compose-split.yml -d

unknown shorthand flag: 'f' in -f
```

>to
```console
docker@packeton:~$ docker-compose -f docker-compose-split.yml up -d

[+] Running 11/11
 ⠿ Network packeton_default         Created                               0.0s
 ⠿ Volume "packeton_postgres-data"  Created                               0.0s
 ⠿ Volume "packeton_app-data"       Created                               0.0s
 ⠿ Volume "packeton_app-var"        Created                               0.0s
 ⠿ Volume "packeton_redis-data"     Created                               0.0s
 ⠿ Container packeton-postgres-1    Started                               0.4s
 ⠿ Container packeton-redis-1       Started                               0.4s
 ⠿ Container packeton-php-fpm-1     Started                               0.6s
 ⠿ Container packeton-cron-1        Started                               1.0s
 ⠿ Container packeton-worker-1      Started                               1.0s
 ⠿ Container packeton-nginx-1       Started                               0.9s
```

4. Create user admin

```console
docker@packeton:~$ docker exec -it packeton-nginx-1 bin/console packagist:user:manager admin --password=123456 --admin
```

## error
![error](https://github.com/vtsykun/packeton/assets/503853/d3fc868f-71b2-4ac2-a576-87aa26297e3f)

I tried to show all the steps followed. If I missed any important information, please let me know!

**Reply by vtsykun** [reply]
Yes, this bug in `docker-compose-split.yml`, I'll fix it later. But now you can use simple `docker-compose.yml` with supervisor or set `APP_SECRET` in your docker-compose-split.yml file. Current value you can see in `.env.local` volume app-data:/data

```yaml
x-environment: &default-environment
    REDIS_URL: redis://redis
    DATABASE_URL: "postgresql://packeton:pack123@postgres:5432/packeton?serverVersion=14&charset=utf8"
    SKIP_INIT: 1
    APP_SECRET: <secret>
```
