### ISSUE TITLE
I try to edit ngix file and then i m using docker-compose-prod.yml but not working

### ISSUE THREAD

**Issue by sunilit42** [vtsykun/packeton#102]
Hello,

I try to set custom domain into ngix file so i need to use docker-compose-prod.yml
but when i use docker-compose-prod.yml, it is not working

Version in "./docker-compose-prod.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by vtsykun** [comment]
Hi
More simple way to setup domain is use nginx proxy in the root host 

you can use simple `docker-compose.yml`

```yml
version: '3.6'

services:
    packeton:
        image: packeton/packeton:latest
        container_name: packeton
        hostname: packeton
        ports:
            - '127.0.0.1:8089:80'
        environment:
            TRUSTED_PROXIES: 172.16.0.0/12
            DATABASE_URL: "mysql://app:!ChangeMe!@ec2-host.example.com:3306/app?serverVersion=8&charset=utf8mb4"
        volumes:
            - .docker:/data

```

Then you need to nginx / apache to the root host and proxy request to local 8089 port - where 8089 

```
        ports:
            - '127.0.0.1:8089:80'
```

Example nginx proxy config is 
```
server {
    listen 443 ssl http2;
    server_name satis.example.org;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/satis.example.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/satis.example.org/privkey.pem; # managed by Certbot
    ssl_session_cache    shared:SSL:10m;
    ssl_session_timeout  10m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256!RC4:!aNULL:!eNULL:!MD5:!EXPORT:!LOW:!SEED:!CAMELLIA:!IDEA:!PSK:!SRP:!SSLv2';

    add_header Strict-Transport-Security max-age=15768000;
    add_header Content-Security-Policy-Report-Only "default-src https:; script-src https: 'unsafe-eval' 'unsafe-inline'; style-src https: 'unsafe-inline'; img-src https: data:; font-src https: data:; report-uri /csp-report";
 
    location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass          http://localhost:8089;
        proxy_read_timeout  90;
    }

}

server {
    if ($host = satis.example.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    return 301 https://$host$request_uri;
    server_name satis.example.org;
}

```

The second why is use `jwilder/nginx-proxy` docker image to step up nginx proxy via docker. Also you may to use `jrcs/letsencrypt-nginx-proxy-companion` docker to get letsencrypt



```yaml 
version: '3.6'

services:
    packeton:
        image: packeton/packeton:latest
        container_name: packeton
        hostname: packeton
        ports:
            - '127.0.0.1:8089:80'
        environment:
            VIRTUAL_HOST: satis.example.com
            LETSENCRYPT_HOST: satis.example.com
            LETSENCRYPT_EMAIL: sysadmin@example.com
    
            TRUSTED_PROXIES: 172.16.0.0/12
            DATABASE_URL: "mysql://app:!ChangeMe!@ec2-host.example.com:3306/app?serverVersion=8&charset=utf8mb4"
        volumes:
            - .docker:/data

networks:
  default:
    external:
      name: webproxy

```

Where VIRTUAL_HOST, LETSENCRYPT_HOST, LETSENCRYPT_EMAIL used for `jrcs/letsencrypt-nginx-proxy-companion` `jwilder/nginx-proxy`
See docs https://hub.docker.com/r/jwilder/nginx-proxy 
https://github.com/jwilder/docker-letsencrypt-nginx-proxy-companion
