### ISSUE TITLE
How to use s3 bucket/persistence storage for storing reposiroty files

### ISSUE THREAD

**Issue by mlalwani6191** [vtsykun/packeton#105]
Hi,
When we submit a package in Packeton it gets stored at **/data/composer/cache/repo** inside the container. Is there a way to use an s3 bucket or any other persistent store to avoid loss of data?

Thanks

**Comment by vtsykun** [comment]
Hi
S3 not supported, Packeton use `composer/composer` which uses local filesystem cache.

But you can mount EBS volume to instance filesystem (if it AWS) for persistent storage and use with docker volumes. `/data` is defined in Dockerfile as data volume.

```
services:
    packagist:
       ...
        volumes:
            - /mnt/storage/data:/data
```
