### ISSUE TITLE
Proxy Packagist.com with read-only token 

### ISSUE THREAD

**Issue by robinero** [vtsykun/packeton#108]
### Description

Hey,

I've encountered a weird issue when trying to proxy/mirror Packagist.com packages with a read-only token.

When setting up the proxy, everything seems to work just fine, but as soon as I try to pull through the packages in a composer project, composer cannot find the packages (in the remote).

I'm not entirely sure if it's Packeton or the read-only token's limitation (as written here: https://packagist.com/docs/setup-ci-cd), but the `/mirror/NAME/packages.json` looks fine if I compare it to https://demo.packeton.org/mirror/packagist/packages.json:

```json
{
    "metadata-url": "/mirror/NAME/p2/%package%.json",
    "metadata-changes-url": "/ORGANISATION/metadata/changes.json",
    "available-packages": [
        "vendor/package",
        ...
    ],
    "mirrors": [
        {
            "dist-url": "/mirror/NAME/zipball/%package%/%version%/%reference%.%type%",
            "preferred": true
        }
    ]
}
```

Do you have any suggestions how I can debug this?

### Can you reproduce the bug on the Packeton demo site?

Not applicable

### Database

PostgreSQL

### How are you running Packeton?

docker compose

**Comment by vtsykun** [comment]
yes, the bug confirmed. I'll provide fixes for it within a few days

**Comment by vtsykun** [comment]
Hi, bug was fixed, you can test with the latest version. My example config for packagist.com 

```yaml
packeton:
    mirrors:
        packagist:
            url: https://repo.packagist.com/org1/
            http_basic:
                username: token
                password: xxxxx
```
