### ISSUE TITLE
Problem with proxy and mirroring some package repositories

### ISSUE THREAD

**Issue by rbouma** [vtsykun/packeton#204]
### Description

We have get this error while updating proxy mirror:

An unexpected failure occurred
Service "amasty" not found: the container inside "Symfony\Component\DependencyInjection\Argument\ServiceLocator" is a smaller service locator that is empty...

config file:
`config/packages/amasty.yaml`

```yaml
packeton:
    mirrors:
        amasty:
            url: https://composer.amasty.com/community/
            http_basic:
              username: 918a8%REDACTED%faa76
              password: 59f92a%REDACTED%05f9
            logo: 'https://commercemarketplace.adobe.com/media/customer/MAG000001054/6523c8eb9134c.png'
```

tried in docker and local system with manual install

### Can you reproduce the bug on the Packeton demo site?

Not applicable

### Database

MySQL

### How are you running Packeton?

Tried with docker:
docker run -d --name packeton \
    --mount type=volume,src=packeton-data,dst=/data \
    -p 8080:80 \
    packeton/packeton:latest

And local manually install on Ubuntu 22.04 server with Mysql 8 and Nginx.
