### ISSUE TITLE
Possibility for caching mirrored repositories

### ISSUE THREAD

**Issue by malinink** [vtsykun/packeton#304]
Is there any possibility to cache mirrored repos zipballs directly in s3?

As for now, i have configured mirror:
```
packeton:
  mirrors:
    packagist:
      url: https://repo.packagist.org
      public_access: true
      sync_lazy: true
```

And s3 provider:
```
      STORAGE_SOURCE: s3
      STORAGE_AWS_BUCKET: test
      STORAGE_AWS_PREFIX: package
      STORAGE_AWS_ARTIFACT_PREFIX: artifact
      STORAGE_AWS_ARGS: '{"endpoint": "http://minio:9000", "accessKeyId": "minioadmin", "accessKeySecret": "minioadmin", "region": "ru-central1"}'
```

It work great, but i found that directory `/data/composer` contains package data and `package` folder in S3 is empty.

I need to setup packeton as stateless service, and my question is:
Is there any possibilities to store packages data that passes via packeton into S3 to cache them?
