### ISSUE TITLE
How to keep database persitance? 

### ISSUE THREAD

**Issue by sunilit42** [vtsykun/packeton#98]
Hello,

we are going to use this service into production and I see we are using docker thing, if we do docker-compose down/stop, that time all data of db will truncate 

That time we will face big issue, how you guys doing on live production env? 

Are you guys using EC2 any service for that ? and use that configuration into docker?

**Comment by vtsykun** [comment]
Hi 
You can use docker env

```
version: '3.6'

services:
    packagist:
        image: packeton/packeton:latest
        container_name: packagist
        hostname: packagist
        environment:
            ....
            DATABASE_URL: "mysql://app:pass@ec2-host.example.com:3306/app?serverVersion=8&charset=utf8mb4"
            REDIS_URL=redis://redishost-example # for redis
            
```

**Comment by vtsykun** [comment]
yes, if you use external EC2 RDS database.

But at the same time, the database data should not be deleted after deleting or restarting the container when used docker database. All permanent data placed into volumes

```
    postgres:
        image: postgres:14-alpine
        hostname: postgres
        <<: *restart_policy
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: packeton
            POSTGRES_PASSWORD: pack123
            POSTGRES_DB: packeton

volumes:
    redis-data:
    postgres-data:
    app-data:
    app-var:
```
